### ISSUE TITLE
flag for "in view" instead of simply on scroll

### ISSUE THREAD

**Issue by troyericg** [sjwilliams/laziestloader#12]
I'm imagining using this in the context of a slideshow, and it would be nice if there could be flag you could set to check for whether an element comes into the viewport from any direction, not just on vertical scroll.

**Comment by sjwilliams** [comment]
@troyericg! I somehow missed this issue. 

I've had the same issue, also for horizontal scroll / slideshows. Let me look into this. It'll be super useful. 

You using laziestloader at The Guardian, by chance?

**Comment by troyericg** [comment]
Not yet! But I am pushing for it because I love it so much.

**Comment by erikreyna** [comment]
+1 on this.

**Comment by sjwilliams** [comment]
@troyericg, @erikreyna I think this is in and good. Holler if you use it and find issues. I've needed this for so long...

**Comment by sjwilliams** [comment]
Oh, and demo: 
http://sjwilliams.github.io/laziestloader/examples/horizontal.html
