### ISSUE TITLE
fadeIn() images on lazyLoad

### ISSUE THREAD

**Issue by petulla** [sjwilliams/laziestloader#13]
Do you have a best practices suggestion for fading in the images upon lazy load?

**Comment by petulla** [comment]
I ended up using a callback on the laziestloader helper. Simple.

```
, function(){
   $(this)
              .css({opacity:0 })
              .animate({opacity: 1}, 400)
});
```

**Comment by sjwilliams** [comment]
@petulla I completely overlooked this! 

You could it that way, but you can also do it with CSS alone, taking advantage of the classes I put on the elements to reflect current state. Something like: 

.ll-init {
  transition: opacity 0.3s ease-out;
  opacity: 0;
}

.ll-loaded {
  opacity: 1;
}

**Comment by petulla** [comment]
Great -- I'll be using that. I also wrote a slideshow module for the loader (and other loaders), which I'll be sharing soon.

**Comment by sjwilliams** [comment]
That's great. Are you, by chance, addressing LaziestLoader's inability to work with horizontal scrolling, not just vertical? It's on my TODO list.
